In [3]:
import qubx
from qubx import logger

%qubxd

%load_ext autoreload
%autoreload 2

from qubx.core.lookups import lookup
from qubx.data.registry import StorageRegistry

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
stor = StorageRegistry.get("ccxt")
r = stor.get_reader("BINANCE.UM", "SWAP")
r1 = stor.get_reader("HYPERLIQUID", "SWAP")

In [6]:
r.get_data_types("BTCUSDT")

[ohlc, funding_payment]

In [7]:
r.read("BTCUSDT", "ohlc(1h)", "-12h", "now").to_pd()

,open,high,low,close,volume,quote_volume
timestamp,,,,,,
2026-02-23 02:00:00,64387.2,64877.2,64273.8,64742.4,14329.587,9.277319e+08
2026-02-23 03:00:00,64742.5,65071.7,64658.0,64894.0,7843.597,5.090024e+08
2026-02-23 04:00:00,64894.1,64989.9,64628.5,64777.3,4946.411,3.204151e+08
2026-02-23 05:00:00,64777.2,65189.3,64768.8,65031.9,6877.930,4.472849e+08
2026-02-23 06:00:00,65031.9,65775.0,64990.8,65717.7,11459.287,7.530780e+08
2026-02-23 07:00:00,65717.7,65980.0,65597.5,65915.8,8197.238,5.403275e+08
2026-02-23 08:00:00,65915.7,65922.9,65534.6,65639.0,6455.790,4.237516e+08
2026-02-23 09:00:00,65639.0,66432.9,65633.8,66374.8,11681.811,7.753779e+08
2026-02-23 10:00:00,66374.9,66574.5,66182.4,66291.1,7254.377,4.809006e+08
2026-02-23 11:00:00,66291.2,66462.1,66072.5,66170.8,5334.809,3.530086e+08
2026-02-23 12:00:00,66170.8,66490.0,65860.9,66249.9,10192.338,6.752414e+08
2026-02-23 13:00:00,66250.0,66360.1,66079.3,66199.0,4823.057,3.192816e+08

In [8]:
r1.read("BTCUSDC", "ohlc(1h)", "-3h", "now").to_pd()

,open,high,low,close,volume,quote_volume
timestamp,,,,,,
2026-02-23 11:00:00,66290.0,66455.0,66065.0,66166.0,1287.62455,8.519697e+07
2026-02-23 12:00:00,66166.0,66472.0,65857.0,66235.0,1997.77033,1.323223e+08
2026-02-23 13:00:00,66236.0,66341.0,66085.0,66199.0,599.92546,3.971447e+07

In [9]:
r.read("BTCUSDT", "funding_payment", "-1d", "now").to_pd()

                     funding_rate  funding_interval_hours
timestamp
2026-02-22 16:00:00      0.000050                     8.0
2026-02-23 00:00:00      0.000069                     8.0
2026-02-23 08:00:00     -0.000093                     8.0

In [11]:
r1.read("BTCUSDC", "funding_payment", "-1d", "now").to_pd()

                     funding_rate  funding_interval_hours
timestamp
2026-02-22 14:00:00  1.250000e-05                     1.0
2026-02-22 15:00:00  8.985200e-06                     1.0
2026-02-22 16:00:00  1.206660e-05                     1.0
2026-02-22 17:00:00  8.091000e-06                     1.0
2026-02-22 18:00:00  4.969000e-07                     1.0
2026-02-22 19:00:00  6.217100e-06                     1.0
2026-02-22 20:00:00  6.507400e-06                     1.0
2026-02-22 21:00:00  4.425800e-06                     1.0
2026-02-22 22:00:00  9.820000e-07                     1.0
2026-02-22 23:00:00 -1.592300e-06                     1.0
2026-02-23 00:00:00 -5.946400e-06                     1.0
2026-02-23 01:00:00 -9.565200e-06                     1.0
2026-02-23 02:00:00  5.847200e-06                     1.0
2026-02-23 03:00:00  5.934500e-06                     1.0
2026-02-23 04:00:00  5.413500e-06                     1.0
2026-02-23 05:00:00  5.600900e-06                     1.0
2026-02-23 06:00:00  1.100230e-05                     1.0
2026-02-23 07:00:00  6.449800e-06                     1.0
2026-02-23 08:00:00  8.224600e-06                     1.0
2026-02-23 09:00:00  5.976600e-06                     1.0
2026-02-23 10:00:00  7.661000e-06                     1.0
2026-02-23 11:00:00  6.123000e-07                     1.0
2026-02-23 12:00:00 -5.011600e-06                     1.0
2026-02-23 13:00:00 -8.376300e-06                     1.0

In [ ]:
from qubx.data.storages.multi import MultiStorage

stor1 = StorageRegistry.get("ccxt")
stor2 = StorageRegistry.get("qdb::quantlab")

In [12]:
s2 = MultiStorage(storages=[stor1, stor2])
s2.get_reader("BINANCE.UM", "SWAP").read("BTCUSDT", "ohlc(1h)", "-3d", "now").to_pd()

ArrowInvalid: Schema at index 1 was different:
timestamp: timestamp[ms]
open: double
high: double
low: double
close: double
volume: double
quote_volume: double
vs
timestamp: timestamp[us]
symbol: string
open: double
high: double
low: double
close: double
volume: double
quote_volume: double
count: int64
taker_buy_volume: double
taker_buy_quote_volume: double